import { Router, type IRouter } from "express";
import healthRouter from "./health";
import ordersRouter from "./orders";
import driversRouter from "./drivers";
import dashboardRouter from "./dashboard";
import activitiesRouter from "./activities";
import alertsRouter from "./alerts";
import resetRequestsRouter from "./reset-requests";
import reviewsRouter from "./reviews";
import restaurantsRouter from "./restaurants";
import playersRouter from "./players";
import clientsRouter from "./clients";
import authRouter from "./auth";
import deliveriesRouter from "./deliveries";
import deliverersRouter from "./deliverers";
import tripsRouter from "./trips";
import pushRouter from "./push";
import statsRouter from "./stats";
import eventsRouter from "./events";
import gameRouter from "./game";
import notificationsRouter from "./notifications";
import livreurRouter from "./livreur";
import gradoRouter from "./grado";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/orders", ordersRouter);
router.use("/drivers", driversRouter);
router.use("/drivers", reviewsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/activities", activitiesRouter);
router.use("/alerts", alertsRouter);
router.use("/reset-requests", resetRequestsRouter);
router.use("/restaurants", restaurantsRouter);
router.use("/players", playersRouter);
router.use("/clients", clientsRouter);
router.use("/deliveries", deliveriesRouter);
router.use("/deliverers", deliverersRouter);
router.use("/trips", tripsRouter);
router.use("/push", pushRouter);
router.use("/stats", statsRouter);
router.use("/events", eventsRouter);
router.use("/game", gameRouter);
router.use("/notifications", notificationsRouter);
router.use("/livreur", livreurRouter);
router.use("/grado", gradoRouter);

export default router;
